### PR TITLE
Add Safari 11.1 to browser support matrix

### PR DESCRIPTION
**Pull request by LinusU**
Safari 11.1 supports directory uploading and thus works with this library.

https://caniuse.com/#feat=input-file-directory

I also tested it myself ☺️

### CODE REVIEW

**Comment by silverwind** [comment]
Indeed, good find. A shame it excludes dotfiles, though :)

**Comment by LinusU** [comment]
> A shame it excludes dotfiles, though :)

According to spec though 😉 but yeah

**Comment by silverwind** [comment]
> According to spec though

Link to said spec?

**Comment by LinusU** [comment]
I could have sworn that I read it when searching around for how to access files in a directory, which eventually led me to this repo, but I cannot seem to find it now 😞 sorry...

**Comment by silverwind** [comment]
I don't think it's part of any spec but some browsers opt to do it to protect their users. Anyways, I noticed that Firefox seems to include dotfiles now, will retest.

**Pull request merged**
